on:
  schedule:
    
cron: "0 18 * * *"
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      
uses: actions/checkout@v3
uses: MoCHivEE/github-profile-3d-contrib@0.7.1
    env:
      GITHUB_TOKEN: ${{ secrets.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
 }}
      USERNAME: ${{ github.MoCHivEE }}
name: Commit & Push
  run: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git add -A .
    git commit -m "generated"
    git push
